CREATE TABLE User (
    id UUID PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    signup_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);


CREATE TABLE Profile (
    id UUID PRIMARY KEY,
    user UUID UNIQUE NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    full_name VARCHAR(50),
    home_town VARCHAR(30),
    phone_number VARCHAR(20)
);

CREATE TABLE Report (
    id UUID PRIMARY KEY,
    subject VARCHAR(50) CHECK (subject IN ('Payments', 'Tickets', 'Delays', 'Other')),
    description TEXT NOT NULL,
    document UUID DEFAULT NULL REFERENCES Document(id) ON DELETE SET NULL,
    user_id UUID NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    inspector UUID NOT NULL REFERENCES User(id) ON DELETE CASCADE,
    is_processed BOOLEAN DEFAULT FALSE,
    processed_at BOOLEAN DEFAULT FALSE,
    responded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Document (
    id UUID PRIMARY KEY,
    file VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user UUID NOT NULL REFERENCES User(id) ON DELETE CASCADE
);

